# Generated by Django 5.2.1 on 2026-05-27 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0010_alter_card_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("set_name", models.CharField(max_length=255)),
                ("set_code", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=50)),
                ("tcgdex_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "price_tracker_card_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "tcgplayer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tcgplayer_url", models.URLField(blank=True, default="")),
                ("rarity", models.CharField(blank=True, default="", max_length=100)),
                ("image_url", models.URLField(blank=True, default="")),
                ("artist", models.CharField(blank=True, default="", max_length=255)),
                ("printings_available", models.JSONField(blank=True, default=list)),
                ("variants", models.JSONField(blank=True, default=dict)),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "regulation_mark",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("standard_legal", models.BooleanField(blank=True, null=True)),
                ("expanded_legal", models.BooleanField(blank=True, null=True)),
                ("tcgdex_raw_data", models.JSONField(blank=True, default=dict)),
                ("price_tracker_raw_data", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="vault_catal_name_639514_idx"),
                    models.Index(
                        fields=["set_name"], name="vault_catal_set_nam_dc2ccd_idx"
                    ),
                    models.Index(
                        fields=["set_code", "card_number"],
                        name="vault_catal_set_cod_ed270c_idx",
                    ),
                    models.Index(
                        fields=["tcgdex_id"], name="vault_catal_tcgdex__ee3fea_idx"
                    ),
                    models.Index(
                        fields=["tcgplayer_id"], name="vault_catal_tcgplay_a53465_idx"
                    ),
                    models.Index(
                        fields=["price_tracker_card_id"],
                        name="vault_catal_price_t_c7d75b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("set_code", "card_number", "name"),
                        name="uniq_catalog_card_identity",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="catalog_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_cards",
                to="vault.catalogcard",
            ),
        ),
    ]
