# Generated by Django 5.2.1 on 2026-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0011_catalogcard_card_catalog_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcard",
            name="price_tracker_card_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="catalogcard",
            name="tcgdex_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="catalogcard",
            name="tcgplayer_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
